import {
  CalendarCheck,
  CalendarDays,
  Check,
  ChevronLeft,
  Clipboard,
  Clock7,
  Coins,
  Film,
  HelpCircle,
  LayoutDashboard,
  Loader2,
  LogOut,
  LucideProps,
  MessageSquare,
  Moon,
  Rocket,
  Settings,
  Star,
  SunMedium,
  Twitter,
  User,
  Video,
  X,
  type Icon as LucideIcon,
} from "lucide-react-native";

export type Icon = LucideIcon;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  twitter: Twitter,
  back: ChevronLeft,
  spinner: Loader2,
  credits: Coins,
  message: MessageSquare,
  user: User,
  film: Film,
  calendar: CalendarDays,
  calendarCheck: CalendarCheck,
  clipboard: Clipboard,
  check: Check,
  settings: Settings,
  help: HelpCircle,
  dashboard: LayoutDashboard,
  logout: LogOut,
  close: X,
  rocket: Rocket,
  star: Star,
  clock: Clock7,
  camera: Video,
};
