import {
  Calendar,
  CalendarCheck,
  Check,
  ChevronLeft,
  Clipboard,
  Coins,
  Film,
  HelpCircle,
  LayoutDashboard,
  Loader2,
  LogOut,
  LucideProps,
  MessageSquare,
  Moon,
  Rocket,
  Settings,
  SunMedium,
  Twitter,
  User,
  X,
  type Icon as LucideIcon,
} from "lucide-react-native";

export type Icon = LucideIcon;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  twitter: Twitter,
  back: ChevronLeft,
  spinner: Loader2,
  credits: Coins,
  message: MessageSquare,
  user: User,
  film: Film,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  clipboard: Clipboard,
  check: Check,
  settings: Settings,
  help: HelpCircle,
  dashboard: LayoutDashboard,
  logout: LogOut,
  close: X,
  rocket: Rocket,
};
